// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dffoo.Server.Data;

#nullable disable

namespace dffoo.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220410112322_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dffoo.Shared.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CPCost")
                        .HasColumnType("int");

                    b.Property<int?>("ChampId")
                        .HasColumnType("int");

                    b.Property<int?>("ChampionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DmgPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.ToTable("Ability");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPCost = 0,
                            Description = "Attacks the targets BRV",
                            DmgPercentage = 100,
                            Name = "Brv Attack",
                            SkillID = ""
                        },
                        new
                        {
                            Id = 2,
                            CPCost = 0,
                            Description = "Attacks the targets HP",
                            DmgPercentage = 100,
                            Name = "HP Attack",
                            SkillID = ""
                        },
                        new
                        {
                            Id = 3,
                            CPCost = 0,
                            ChampId = 34,
                            Description = "3-hit Melee BRV attack. High turn rate",
                            DmgPercentage = 105,
                            Name = "Quick Hit",
                            SkillID = "S1"
                        },
                        new
                        {
                            Id = 4,
                            CPCost = 0,
                            ChampId = 34,
                            Description = "2-Hit Melee BRV attack. Target: Fair chance 5 turns SPD Down I",
                            DmgPercentage = 120,
                            Name = "Slash",
                            SkillID = "S2"
                        },
                        new
                        {
                            Id = 5,
                            CPCost = 0,
                            ChampId = 34,
                            Description = "2-hit Melee BRV attack + HP attack. Extends own buffs 2 turns",
                            DmgPercentage = 150,
                            Name = "Buff Longer Slash",
                            SkillID = "AA"
                        },
                        new
                        {
                            Id = 6,
                            CPCost = 0,
                            ChampId = 34,
                            Description = "6-hit group ranged BRV attack + group HP attack. BRV attacks distributed based on number of enemies. Deals total HP damage to each target. Self: 5 turns ATK Up II, SPD Up I",
                            DmgPercentage = 390,
                            Name = "Energy Rain",
                            SkillID = "EX"
                        });
                });

            modelBuilder.Entity("dffoo.Shared.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ATK")
                        .HasColumnType("int");

                    b.Property<bool>("BT")
                        .HasColumnType("bit");

                    b.Property<bool>("BTplus")
                        .HasColumnType("bit");

                    b.Property<int>("ChampClevel")
                        .HasColumnType("int");

                    b.Property<string>("ChampCrystal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampSphere1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampSphere2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampSphere3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEF")
                        .HasColumnType("int");

                    b.Property<bool>("EX")
                        .HasColumnType("bit");

                    b.Property<bool>("EXplus")
                        .HasColumnType("bit");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("HG35")
                        .HasColumnType("bit");

                    b.Property<bool>("HG7star")
                        .HasColumnType("bit");

                    b.Property<bool>("HG7starPlus")
                        .HasColumnType("bit");

                    b.Property<bool>("HG90")
                        .HasColumnType("bit");

                    b.Property<bool>("HG90plus")
                        .HasColumnType("bit");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("IBRV")
                        .HasColumnType("int");

                    b.Property<bool>("LD")
                        .HasColumnType("bit");

                    b.Property<int>("MBRV")
                        .HasColumnType("int");

                    b.Property<bool>("ManikinWeapon")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCP")
                        .HasColumnType("int");

                    b.Property<bool>("UltimaWeapon")
                        .HasColumnType("bit");

                    b.Property<bool>("W15cp")
                        .HasColumnType("bit");

                    b.Property<bool>("W35cp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ATK = 3517,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Warrior Of Light",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 6024,
                            EX = true,
                            EXplus = false,
                            GameId = 1,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13955,
                            IBRV = 5081,
                            LD = true,
                            MBRV = 10262,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 2,
                            ATK = 3517,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Black",
                            ChampName = "Vivi",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 6024,
                            EX = true,
                            EXplus = false,
                            GameId = 9,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13955,
                            IBRV = 5081,
                            LD = true,
                            MBRV = 10262,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 58,
                            ATK = 3517,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Black",
                            ChampName = "Garnet",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 6024,
                            EX = true,
                            EXplus = false,
                            GameId = 9,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13955,
                            IBRV = 5081,
                            LD = true,
                            MBRV = 10262,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 3,
                            ATK = 3517,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Green",
                            ChampName = "Rem",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Dagger",
                            DEF = 6024,
                            EX = true,
                            EXplus = false,
                            GameId = 17,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13955,
                            IBRV = 5081,
                            LD = true,
                            MBRV = 10262,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 4,
                            ATK = 3517,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Red",
                            ChampName = "Sazh",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Gun",
                            DEF = 6024,
                            EX = true,
                            EXplus = false,
                            GameId = 13,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13955,
                            IBRV = 5081,
                            LD = true,
                            MBRV = 10262,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 5,
                            ATK = 3532,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Yellow",
                            ChampName = "Tifa",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "fist",
                            DEF = 5116,
                            EX = true,
                            EXplus = false,
                            GameId = 7,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 12508,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 11475,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 6,
                            ATK = 3759,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Blue",
                            ChampName = "Cloud",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Greatsword",
                            DEF = 5029,
                            EX = true,
                            EXplus = false,
                            GameId = 7,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13171,
                            IBRV = 4355,
                            LD = true,
                            MBRV = 11314,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 7,
                            ATK = 3497,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Hope",
                            ChampSphere1 = "B",
                            ChampSphere2 = "C",
                            ChampSphere3 = "D",
                            ChampType = "shuriken",
                            DEF = 5029,
                            EX = true,
                            EXplus = false,
                            GameId = 13,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13259,
                            IBRV = 4810,
                            LD = true,
                            MBRV = 11133,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 8,
                            ATK = 3482,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Yshtola",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "staff",
                            DEF = 5340,
                            EX = true,
                            EXplus = false,
                            GameId = 14,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 14018,
                            IBRV = 5136,
                            LD = true,
                            MBRV = 10276,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 9,
                            ATK = 3533,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 80,
                            ChampCrystal = "blue",
                            ChampName = "Zidane",
                            ChampSphere1 = "A",
                            ChampSphere2 = "A",
                            ChampSphere3 = "E",
                            ChampType = "dagger",
                            DEF = 5029,
                            EX = true,
                            EXplus = false,
                            GameId = 9,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13243,
                            IBRV = 4147,
                            LD = true,
                            MBRV = 11237,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 10,
                            ATK = 3592,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Black",
                            ChampName = "Cecil (Dark Knight)",
                            ChampSphere1 = "A",
                            ChampSphere2 = "C",
                            ChampSphere3 = "E",
                            ChampType = "Greatsword",
                            DEF = 5029,
                            EX = true,
                            EXplus = false,
                            GameId = 4,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 15644,
                            IBRV = 3850,
                            LD = true,
                            MBRV = 10449,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 11,
                            ATK = 3568,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Green",
                            ChampName = "Yda",
                            ChampSphere1 = "A",
                            ChampSphere2 = "A",
                            ChampSphere3 = "E",
                            ChampType = "fist",
                            DEF = 5037,
                            EX = true,
                            EXplus = false,
                            GameId = 14,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13180,
                            IBRV = 4037,
                            LD = true,
                            MBRV = 11372,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 12,
                            ATK = 3590,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Red",
                            ChampName = "Vaan",
                            ChampSphere1 = "A",
                            ChampSphere2 = "A",
                            ChampSphere3 = "E",
                            ChampType = "Sword",
                            DEF = 5113,
                            EX = true,
                            EXplus = false,
                            GameId = 12,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 12483,
                            IBRV = 4663,
                            LD = true,
                            MBRV = 12266,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 13,
                            ATK = 3466,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Red",
                            ChampName = "Yuffie",
                            ChampSphere1 = "D",
                            ChampSphere2 = "E",
                            ChampSphere3 = "E",
                            ChampType = "shuriken",
                            DEF = 5029,
                            EX = true,
                            EXplus = false,
                            GameId = 7,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13252,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 12081,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 14,
                            ATK = 3394,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Yuna",
                            ChampSphere1 = "C",
                            ChampSphere2 = "C",
                            ChampSphere3 = "D",
                            ChampType = "Staff",
                            DEF = 5650,
                            EX = true,
                            EXplus = false,
                            GameId = 10,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 15074,
                            IBRV = 5063,
                            LD = true,
                            MBRV = 9558,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 15,
                            ATK = 3461,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Blue",
                            ChampName = "Edge",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "D",
                            ChampType = "Dagger",
                            DEF = 4533,
                            EX = true,
                            EXplus = false,
                            GameId = 4,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13202,
                            IBRV = 4810,
                            LD = false,
                            MBRV = 11152,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 16,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "King",
                            ChampSphere1 = "A",
                            ChampSphere2 = "A",
                            ChampSphere3 = "D",
                            ChampType = "Gun",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 17,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = false,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 17,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Bartz",
                            ChampSphere1 = "A",
                            ChampSphere2 = "C",
                            ChampSphere3 = "D",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 5,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 18,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Penelo",
                            ChampSphere1 = "C",
                            ChampSphere2 = "C",
                            ChampSphere3 = "D",
                            ChampType = "Dagger",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 12,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 19,
                            ATK = 3640,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Terra",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 20,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Yang",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Fist",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 4,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 21,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Red",
                            ChampName = "Onion Knight",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 3,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 22,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Red",
                            ChampName = "Firion",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 2,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 23,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Blue",
                            ChampName = "Laguna",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Gun",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 8,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = false,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 24,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Green",
                            ChampName = "Steiner",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Greatsword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 9,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 25,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Shadow",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Shuriken",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 26,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Black",
                            ChampName = "Squall",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Greatsword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 8,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 27,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Red",
                            ChampName = "Vanille",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 13,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 28,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Setzer",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Shuriken",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 29,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Blue",
                            ChampName = "Wakka",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Shuriken",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 30,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Breen",
                            ChampName = "Galuf",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Greatsword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 5,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 31,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Shantotto",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 11,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 32,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Balthier",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Gun",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 12,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 33,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "White",
                            ChampName = "Eiko",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 9,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 34,
                            ATK = 4151,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Blue",
                            ChampName = "Tidus",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4722,
                            EX = true,
                            EXplus = false,
                            GameId = 10,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 16179,
                            IBRV = 5530,
                            LD = true,
                            MBRV = 12147,
                            ManikinWeapon = true,
                            MaxCP = 775,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 35,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Red",
                            ChampName = "Zell",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Fist",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 8,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 36,
                            ATK = 3640,
                            BT = true,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Layle",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Shuriken",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 16,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 37,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Vincent",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Gun",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 7,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 38,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Prishe",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Fist",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 11,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = false,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 39,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Blue",
                            ChampName = "Faris",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Dagger",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 5,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 40,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Yellow",
                            ChampName = "Razma",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 19,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 41,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 80,
                            ChampCrystal = "Yellow",
                            ChampName = "Ace",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Shuriken",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 17,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 42,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Seymour",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 10,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = false,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 43,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Black",
                            ChampName = "Sabin",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Fist",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 44,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Blue",
                            ChampName = "Krile",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 5,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 45,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Blue",
                            ChampName = "Cyan",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Greatsword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 6,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 46,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Red",
                            ChampName = "Papalymo",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Staff",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 14,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 47,
                            ATK = 3640,
                            BT = true,
                            BTplus = true,
                            ChampClevel = 90,
                            ChampCrystal = "Yellow",
                            ChampName = "Lightning",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Sword",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 13,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = true,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 48,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "White",
                            ChampName = "Thancred",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Dagger",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 11,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = false,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = false,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 49,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 80,
                            ChampCrystal = "Green",
                            ChampName = "Snow",
                            ChampSphere1 = "A",
                            ChampSphere2 = "B",
                            ChampSphere3 = "C",
                            ChampType = "Fist",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 13,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        },
                        new
                        {
                            Id = 50,
                            ATK = 3640,
                            BT = false,
                            BTplus = false,
                            ChampClevel = 90,
                            ChampCrystal = "Yellow",
                            ChampName = "Cater",
                            ChampSphere1 = "A",
                            ChampSphere2 = "A",
                            ChampSphere3 = "E",
                            ChampType = "Gun",
                            DEF = 4616,
                            EX = true,
                            EXplus = true,
                            GameId = 17,
                            HG35 = true,
                            HG7star = true,
                            HG7starPlus = true,
                            HG90 = true,
                            HG90plus = true,
                            HP = 13255,
                            IBRV = 4339,
                            LD = true,
                            MBRV = 10474,
                            ManikinWeapon = false,
                            UltimaWeapon = false,
                            W15cp = true,
                            W35cp = true
                        });
                });

            modelBuilder.Entity("dffoo.Shared.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Final Fantasy 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Final Fantasy 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Final Fantasy 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Final Fantasy 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Final Fantasy 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Final Fantasy 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Final Fantasy 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Final Fantasy 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Final Fantasy 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Final Fantasy 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Final Fantasy 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Final Fantasy 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Final Fantasy 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Final Fantasy 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Final Fantasy 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Final Fantasy Crystal Chronicles"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Final Fantasy Type-0"
                        },
                        new
                        {
                            Id = 18,
                            Name = "World Of Final Fantasy"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Final Fantasy Tactics"
                        });
                });

            modelBuilder.Entity("dffoo.Shared.Sphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sphere");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChampionId = 34,
                            Description = "When inflicting Break or attacking target afflicted with Break while own HP at MAX: Inflicts 6 turns SPD Down 20% on selected target",
                            Letter = "E",
                            Name = "Full HP Break Hit Speed Down"
                        },
                        new
                        {
                            Id = 2,
                            ChampionId = 16,
                            Description = "Raises own Atk by 20% for 3 turns when inflicting Break. Does not stack with same Sphere",
                            Letter = "A",
                            Name = "Break Attack Up Shorter"
                        },
                        new
                        {
                            Id = 3,
                            ChampionId = 65,
                            Description = "When inflicting Break or attacking target afflicted with Break: Raises own PHY ATK by 15% for 6 Turns",
                            Letter = "A",
                            Name = "Break Hit Physical Attack Up Longer"
                        },
                        new
                        {
                            Id = 4,
                            ChampionId = 42,
                            Description = "When inflicting debuff on target: Raises own ATK by 3% up to 5 times, once per turn",
                            Letter = "E",
                            Name = "Debuff Success Raging Attack"
                        });
                });

            modelBuilder.Entity("dffoo.Shared.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dffoo.Shared.Ability", b =>
                {
                    b.HasOne("dffoo.Shared.Champion", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId");

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("dffoo.Shared.Champion", b =>
                {
                    b.HasOne("dffoo.Shared.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
